/** @file functions_header.h */
//
// Created by Bartek
//
#ifndef INC_2A61D9D6_GR04_REPO_FUNCTIONS_HEADER_H
#define INC_2A61D9D6_GR04_REPO_FUNCTIONS_HEADER_H

#include <vector>
#include <string>
#include "structures.h"

/**
	* @file
    * @brief Contains function declarations for reading, processing, and printing labeled point sets.
	*/

/**
* @brief Reads a file and populates a sets_of_points object with the contents.
*
* @param file_name The name of the file to read.
* @param points A reference to a sets_of_points object to populate with the read data.
* @param is_test_file A boolean value indicating whether the file being read is a test file.
*/

void read_file(const std::string& file_name, sets_of_points& points, const bool is_test_file);

/**
 * @brief Implements the K-Nearest Neighbors algorithm for a sets_of_points object.
 *
 * @param points A sets_of_points object containing the labeled points to use in the algorithm.
 * @param k_value An integer value specifying the number of neighbors to consider.
 *
 * @return A sets_of_points object containing the predictions generated by the algorithm.
 */

sets_of_points algorithm_KNN(sets_of_points points, int k_value);

/**
 * @brief Prints the labeled points in a sets_of_points object to a file.
 *
 * @param file_name The name of the file to write the labeled points to.
 * @param labeled_points A const reference to a sets_of_points object containing the labeled points to print.
 */

void print_results(const std::string& file_name, const sets_of_points& labeled_points);

#endif //INC_2A61D9D6_GR04_REPO_FUNCTIONS_HEADER_H
